DIRECTORY = 'user_data/'

FILE_HABIT_TASK_COMPLETIONS = 'habit_tasks_completions.json'
FILE_HABIT_TASKS = 'habit_tasks.json'
FILE_RUNTIME_LOGS = 'runtime_logs.json'
FILE_TASK_COMPLETIONS = 'task_completions.json'
FILE_TASK_HABITS = 'task_habits.json'
FILE_TASKS = 'tasks.json'

FILE_PATH_HABIT_TASK_COMPLETIONS = f'{DIRECTORY}{FILE_HABIT_TASK_COMPLETIONS}'
FILE_PATH_HABIT_TASKS = f'{DIRECTORY}{FILE_HABIT_TASKS}'
FILE_PATH_RUNTIME_LOGS = f'{DIRECTORY}{FILE_RUNTIME_LOGS}'
FILE_PATH_TASK_COMPLETIONS = f'{DIRECTORY}{FILE_TASK_COMPLETIONS}'
FILE_PATH_TASK_HABITS = f'{DIRECTORY}{FILE_TASK_HABITS}'
FILE_PATH_TASKS = f'{DIRECTORY}{FILE_TASKS}'

MODE_READ = 'r'
MODE_WRITE = 'w'

INDENT = 4

FORMAT_TIMESTAMP = '%Y-%m-%d %H:%M:%S'
FORMAT_DATE_TIME_PRECISE = '%Y-%m-%dT%H:%M:%S.000000Z'
