DIRECTORY = 'user_data/'

FILE_HABIT_TASK_COMPLETIONS = 'habit_tasks_completions.json'
FILE_HABIT_TASKS = 'habit_tasks.json'
FILE_HABITIFY_UPDATES = 'habitify_updates.csv'
FILE_TASK_COMPLETIONS = 'task_completions.json'

FILE_PATH_HABIT_TASK_COMPLETIONS = f'{DIRECTORY}{FILE_HABIT_TASK_COMPLETIONS}'
FILE_PATH_HABIT_TASKS = f'{DIRECTORY}{FILE_HABIT_TASKS}'
FILE_PATH_HABITIFY_UPDATES = f'{DIRECTORY}{FILE_HABITIFY_UPDATES}'
FILE_PATH_TASK_COMPLETIONS = f'{DIRECTORY}{FILE_TASK_COMPLETIONS}'

MODE_APPEND = 'a'
MODE_READ = 'r'
MODE_WRITE = 'w'

FORMAT_TIMESTAMP = '%Y-%m-%d %H:%M:%S'
