DIRECTORY = 'user_data/'

FILE_HABIT_TASK_COMPLETIONS = 'habit_tasks_completions.json'
FILE_HABIT_TASKS = 'habit_tasks.json'
FILE_TASK_COMPLETIONS = 'task_completions.json'

FILE_PATH_HABIT_TASK_COMPLETIONS = f'{DIRECTORY}{FILE_HABIT_TASK_COMPLETIONS}'
FILE_PATH_HABIT_TASKS = f'{DIRECTORY}{FILE_HABIT_TASKS}'
FILE_PATH_TASK_COMPLETIONS = f'{DIRECTORY}{FILE_TASK_COMPLETIONS}'

CODE_READ = 'r'
CODE_WRITE = 'w'
